#!/usr/bin/env python3
"""train_zero.py — AlphaZero/KataGo-style self-play training on the
lowest-complexity variant of every topology, headless.

(A note on names: real KataGo networks are CNNs over rectangles and cannot
see these boards at all. This is the KataGo *method* — policy+value network,
PUCT self-play, replay buffer — applied to a graph network that plays every
surface. One net trains across all specs because it only ever reads the
adjacency graph.)

    python3 train_zero.py --iters 100                 # all lowest topologies
    python3 train_zero.py --specs sphere,klein --sims 64

Checkpoints land in python/train/checkpoints/zero_mini.npz; the bridge bot
bots/zero_mini.py serves the latest automatically.
"""

from __future__ import annotations

import argparse
import os
import random
import sys
import time
from collections import deque

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from env import (INCIDENCE_MODES, LOWEST, SPECS, adjacency,      # noqa: E402
                 board_for, new_game, play_game, random_agent)
from mcts import MCTS, policy_target                              # noqa: E402
from zeronet import ZeroNet, features, mean_matrix                # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
CKPT_DIR = os.path.join(HERE, "checkpoints")
ROOT = os.path.dirname(os.path.dirname(HERE))

ZERO_MODEL_JS = """// Auto-generated by python/train/train_zero.py --export-web.
// The zero-style graph net running natively in the page: WEIGHTS carries the
// trained parameters (inlined by the build from the sibling .weights.json).
// The forward pass mirrors python/train/zeronet.py exactly.
(function () {
  if (!WEIGHTS) return;   // no .weights.json beside this model: stay unlisted
  const P = WEIGHTS.params, L = WEIGHTS.layers, D = WEIGHTS.hidden;

  function forward(adj, stones, toMove, mask) {
    const n = adj.length;
    let md = 1;
    for (let v = 0; v < n; v++) md = Math.max(md, adj[v].length);
    let H = new Array(n);                       // features -> first layer
    for (let v = 0; v < n; v++) {
      const c = stones[v];
      const x = [c === toMove ? 1 : 0, (c && c !== toMove) ? 1 : 0,
                 c === 0 ? 1 : 0, adj[v].length / md, 1];
      const h = new Float64Array(D);
      for (let j = 0; j < D; j++) {
        let s = P.b0[j];
        for (let i = 0; i < 5; i++) s += x[i] * P.W0[i][j];
        h[j] = s > 0 ? s : 0;
      }
      H[v] = h;
    }
    for (let l = 0; l < L; l++) {
      const Ws = P["Ws" + l], Wn = P["Wn" + l], b = P["b" + (l + 1)];
      const AH = new Array(n);
      for (let v = 0; v < n; v++) {
        const m = new Float64Array(D), a = adj[v];
        for (let k = 0; k < a.length; k++) {
          const hu = H[a[k]];
          for (let j = 0; j < D; j++) m[j] += hu[j];
        }
        if (a.length) for (let j = 0; j < D; j++) m[j] /= a.length;
        AH[v] = m;
      }
      const H2 = new Array(n);
      for (let v = 0; v < n; v++) {
        const h = new Float64Array(D);
        for (let j = 0; j < D; j++) {
          let s = b[j];
          for (let i = 0; i < D; i++)
            s += H[v][i] * Ws[i][j] + AH[v][i] * Wn[i][j];
          h[j] = s > 0 ? s : 0;
        }
        H2[v] = h;
      }
      H = H2;
    }
    const g = new Float64Array(D);
    for (let v = 0; v < n; v++)
      for (let j = 0; j < D; j++) g[j] += H[v][j] / n;
    const logits = new Float64Array(n + 1);
    for (let v = 0; v < n; v++) {
      let s = P.bp[0];
      for (let j = 0; j < D; j++) s += H[v][j] * P.wp[j];
      logits[v] = s;
    }
    let pl = P.bq[0], u = P.bv[0];
    for (let j = 0; j < D; j++) { pl += g[j] * P.wq[j]; u += g[j] * P.wv[j]; }
    logits[n] = pl;
    let mx = -Infinity;
    for (let i = 0; i <= n; i++) if (mask[i]) mx = Math.max(mx, logits[i]);
    let Z = 0;
    const probs = new Float64Array(n + 1);
    for (let i = 0; i <= n; i++) {
      probs[i] = mask[i] ? Math.exp(logits[i] - mx) : 0;
      Z += probs[i];
    }
    for (let i = 0; i <= n; i++) probs[i] /= Z || 1;
    return { probs, value: Math.tanh(u) };
  }

  GeoAI.models.push({
    id: __ID__,
    name: __NAME__,
    levels: ["casual", "standard"],
    supports: __SUPPORTS__,
    create(neighbors, opts) {
      const level = (opts && opts.level) || "standard";
      return {
        forward(stones, color, mask) { return forward(neighbors, stones, color, mask); },
        pickMove(stones, color, o) {
          const n = neighbors.length;
          const legal = (o && o.legalMask) || null;
          const mask = new Uint8Array(n + 1);
          mask[n] = 1;
          for (let v = 0; v < n; v++)
            if (stones[v] === 0 && (!legal || legal[v])) mask[v] = 1;
          const { probs, value } = forward(neighbors, stones, color, mask);
          let a = n;
          if (level === "casual") {
            let r = Math.random();
            for (let i = 0; i <= n; i++) { r -= probs[i]; if (r <= 0) { a = i; break; } }
          } else {
            let best = -1;
            for (let i = 0; i <= n; i++)
              if (probs[i] > best) { best = probs[i]; a = i; }
          }
          return { move: a === n ? -1 : a,
                   value, reason: "zero policy v" + value.toFixed(2) };
        },
      };
    },
  });
})();
"""


def export_web(net, out_id, name=None):
    """Write the trained net as a browser-native model into web/models/."""
    mdir = os.path.join(ROOT, "web", "models")
    os.makedirs(mdir, exist_ok=True)
    payload = {
        "hidden": net.hidden, "layers": net.layers,
        "meta": net.meta,
        "params": {k: v.tolist() for k, v in net.p.items()},
    }
    import json as _json
    with open(os.path.join(mdir, f"{out_id}.weights.json"), "w") as f:
        _json.dump(payload, f)
    supports = {"surfaces": net.meta.get("surfaces"),
                "meshes": net.meta.get("meshes"),
                # every incidence structure the weights were trained on
                "incidence": net.meta.get("incidence") or ["vertices"]}
    js = (ZERO_MODEL_JS
          .replace("WEIGHTS.params", "WEIGHTS.params")
          .replace("__ID__", _json.dumps(out_id))
          .replace("__NAME__", _json.dumps(name or "Zero " + out_id))
          .replace("__SUPPORTS__", _json.dumps(supports)))
    with open(os.path.join(mdir, f"{out_id}.js"), "w") as f:
        f.write(js)
    print(f"exported web/models/{out_id}.js + .weights.json "
          f"(surfaces: {','.join(supports['surfaces'] or [])}) "
          "-- run `node build.mjs ../geodesics.html` in web/")


def self_play_game(net, key, boards, sims, seed, temp_moves=10,
                   incidence="vertices"):
    # the game must live on the SAME graph the network reads: a
    # derived (edges/faces/cells) board has a different site count
    # than its vertex parent, so incidence is threaded through here
    game = new_game(key, incidence=incidence)
    board, A = boards[key]
    tree = MCTS(net, board, A, seed=seed)
    records = []
    move_no = 0
    while not game.game_over and move_no < 4 * board.n:
        counts = tree.run(game, sims)
        if move_no < board.n // 2 and counts[:board.n].sum() > 0:
            counts = counts.copy()          # no early passing in self-play
            counts[board.n] = 0             # (Tromp-Taylor + komi makes
        tau = 1.0 if move_no < temp_moves else 0.0   # early pass-pass a
        pi = policy_target(counts, tau)              # degenerate White win)
        mask = np.zeros(board.n + 1)
        mask[board.n] = 1
        for v in game.legal_moves():
            mask[v] = 1
        records.append({"key": key, "stones": tuple(game.colors),
                        "to_move": game.to_move, "mask": mask, "pi": pi,
                        "player": game.to_move})
        a = int(np.random.default_rng(seed * 7 + move_no).choice(
            board.n + 1, p=pi)) if tau > 0 else int(np.argmax(pi))
        if a == board.n or not game.is_legal(a):
            game.play_pass()
        else:
            game.play(a)
        move_no += 1
    winner = game.score()["winner"]
    z = {"B": 1, "W": 2}.get(winner)
    for r in records:
        r["z"] = 0.0 if z is None else (1.0 if r["player"] == z else -1.0)
    return records, winner, move_no


def eval_vs_random(net, key, boards, games, seed,
                   incidence="vertices"):
    board, A = boards[key]
    wins = 0.0
    for g in range(games):
        game = new_game(key, incidence=incidence)

        def net_agent(gm, color):
            mask = np.zeros(board.n + 1)
            mask[board.n] = 1
            legal = gm.legal_moves()
            for v in legal:
                mask[v] = 1
            if not legal:
                return -1
            X = features(board.adj, gm.colors, color)
            probs, _, _ = net.forward(A, X, mask)
            a = int(np.argmax(probs[:board.n]))     # prefer playing to passing
            return a if probs[a] > 0 else -1

        rnd = random_agent(random.Random(seed * 31 + g))
        black, white = (net_agent, rnd) if g % 2 == 0 else (rnd, net_agent)
        winner, _ = play_game(game, black, white)
        net_is_black = g % 2 == 0
        if winner == "draw":
            wins += 0.5
        elif (winner == "B") == net_is_black:
            wins += 1.0
    return wins / games


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--specs", default="lowest",
                    help=f"'lowest' or comma list of {', '.join(SPECS)}")
    ap.add_argument("--incidence", default="vertices",
                    choices=INCIDENCE_MODES,
                    help="which cells of each board's mesh are the playable "
                         "sites: vertices (canonical Go), edges (the line "
                         "graph), faces (the dual graph), or cells (the "
                         "Hasse diagram). The network only ever reads the "
                         "adjacency graph, so one flag re-targets every "
                         "spec in the run; 'faces'/'cells' require a "
                         "complete face complex and exit with the "
                         "offending spec named otherwise")
    ap.add_argument("--iters", type=int, default=50)
    ap.add_argument("--games-per-iter", type=int, default=8)
    ap.add_argument("--sims", type=int, default=48)
    ap.add_argument("--hidden", type=int, default=32)
    ap.add_argument("--layers", type=int, default=3)
    ap.add_argument("--batch", type=int, default=48)
    ap.add_argument("--steps-per-iter", type=int, default=80)
    ap.add_argument("--buffer", type=int, default=20000)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--eval-every", type=int, default=5)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--checkpoint", default=os.path.join(CKPT_DIR,
                                                         "zero_mini.npz"))
    ap.add_argument("--resume", default=None, metavar="CKPT",
                    help="warm-start weights from a checkpoint; its "
                         "--hidden/--layers override the CLI (for curriculum)")
    ap.add_argument("--export-web", default=None, metavar="MODEL_ID",
                    help="after training, also export a browser-native model "
                         "into web/models/ under this id")
    args = ap.parse_args()

    keys = LOWEST if args.specs == "lowest" else args.specs.split(",")
    for k in keys:
        if k not in SPECS:
            sys.exit(f"unknown spec '{k}'")
    boards = {}
    for k in keys:
        try:                                    # incidence re-targets every spec
            b = board_for(k, incidence=args.incidence)
        except ValueError as e:                 # e.g. faces on an open honeycomb
            sys.exit(f"--incidence {args.incidence}: {e}")
        boards[k] = (b, mean_matrix(b.adj))
    if args.resume:
        if not os.path.isfile(args.resume):
            sys.exit(f"--resume: no checkpoint at {args.resume}")
        net = ZeroNet.load(args.resume)
        if net.hidden != args.hidden or net.layers != args.layers:
            print(f"resume: using checkpoint architecture hidden={net.hidden} "
                  f"layers={net.layers} (CLI ignored)")
        print(f"resumed from {args.resume} "
              f"(previously trained on {net.meta.get('specs', 'unknown')})")
    else:
        net = ZeroNet(hidden=args.hidden, layers=args.layers, seed=args.seed)
    # union provenance across resumes: a curriculum's exported supports must
    # cover every board (and every incidence structure) the weights ever saw
    seen = sorted(set(net.meta.get("specs", [])) | set(keys)) \
        if args.resume else keys
    seen_inc = sorted(set(net.meta.get("incidence", []))
                      | {args.incidence}) if args.resume else [args.incidence]
    net.meta = {"specs": seen,
                "surfaces": sorted({SPECS[k][0] for k in seen}),
                "meshes": sorted({SPECS[k][1] for k in seen}),
                "incidence": seen_inc}
    buf = deque(maxlen=args.buffer)
    rng = np.random.default_rng(args.seed)
    os.makedirs(CKPT_DIR, exist_ok=True)

    print(f"zero-style training on {keys} "
          f"({', '.join(f'{k}:{boards[k][0].n}v' for k in keys)}); "
          f"sites on {args.incidence}; "
          f"{args.sims} sims, hidden {args.hidden}x{args.layers}")
    for it in range(1, args.iters + 1):
        t0 = time.time()
        winners = []
        for g in range(args.games_per_iter):
            key = keys[(it * args.games_per_iter + g) % len(keys)]
            recs, winner, moves = self_play_game(
                net, key, boards, args.sims,
                seed=args.seed * 100 + it * 17 + g,
                incidence=args.incidence)
            buf.extend(recs)
            winners.append(winner)
        losses = []
        for _ in range(args.steps_per_iter):
            batch = [buf[i] for i in rng.integers(0, len(buf), args.batch)]
            grads = net.zero_grads()
            total = 0.0
            for r in batch:
                board, A = boards[r["key"]]
                X = features(board.adj, r["stones"], r["to_move"])
                _, _, cache = net.forward(A, X, r["mask"])
                total += net.backward(cache, r["pi"], r["z"], grads)
            for k in grads:
                grads[k] /= len(batch)
            net.adam_step(grads, lr=args.lr)
            losses.append(total / len(batch))
        line = (f"iter {it:3d}  buffer {len(buf):5d}  "
                f"loss {np.mean(losses):.3f}  "
                f"B/W {winners.count('B')}/{winners.count('W')}  "
                f"{time.time() - t0:.0f}s")
        if it % args.eval_every == 0 or it == args.iters:
            wr = np.mean([eval_vs_random(net, k, boards, 6,
                                         seed=args.seed + it,
                                         incidence=args.incidence)
                          for k in keys])
            line += f"  | vs random: {wr:.2f}"
            net.save(args.checkpoint)
            line += "  [checkpoint]"
        print(line, flush=True)
    net.save(args.checkpoint)
    print(f"saved {args.checkpoint} — the bridge bot bots/zero_mini.py "
          "now serves it")
    if args.export_web:
        export_web(net, args.export_web)


if __name__ == "__main__":
    main()
