#!/usr/bin/env python3
"""train_hgnn.py — self-play optimization of the hierarchical (MSC) engine.

The browser engine's ~35 scalar weights (head, diffusion blocks, MSC mixes,
pyramid mixes, sigma) are optimized by a cross-entropy method: sample weight
vectors around the current mean, score each by win-rate against the current
mean over self-play games on the chosen boards, and move the mean toward the
elites. Derivative-free on purpose — pickMove contains argmax lookahead, so
this is the honest optimizer for it, and there is nothing to install.

Train one instance per topology ("independently") or one across a pool:

    python3 train_hgnn.py --boards sphere --generations 60 --out hgnn-sphere
    python3 train_hgnn.py --boards lowest --generations 80 --out hgnn-all

Export drops <out>.weights.json + <out>.js into web/models/, so the next
`node build.mjs` puts the trained model in the app's Opponent menu.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from env import LOWEST, SPECS, adjacency, new_game, play_game   # noqa: E402
from hgnn import (DEFAULT_WEIGHTS, Engine, flatten_weights,      # noqa: E402
                  unflatten_weights)

ROOT = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))

MODEL_JS = """// Auto-generated by python/train/train_hgnn.py — do not edit.
// Trained instance of the built-in hierarchical engine; WEIGHTS is inlined
// by the build from the sibling .weights.json.
GeoAI.models.push({{
  id: {id!r},
  name: {name!r},
  levels: ["standard"],
  create(neighbors, opts) {{
    const e = GeoAI.createEngine(neighbors, opts);
    if (WEIGHTS) e.setWeights(WEIGHTS);
    return e;
  }},
}});
"""


def make_agent(adj, weights, seed):
    eng = Engine(adj, level="standard", seed=seed, weights=weights,
                 select={"temp": 0.3, "noise": 0.08, "topk": 8})

    def agent(game, color):
        mask = [0] * game.board.n
        for v in game.legal_moves():
            mask[v] = 1
        return eng.pick_move(game.colors, color, legal_mask=mask)["move"]
    return agent


def match(w_a, w_b, board_keys, games, seed):
    """Score of A vs B over `games` self-play games (win 1, draw 0.5),
    alternating colors and cycling board specs."""
    score = 0.0
    boards = {k: adjacency(new_game(k).board) for k in board_keys}
    for g in range(games):
        key = board_keys[g % len(board_keys)]
        game = new_game(key)
        adj = boards[key]
        s = seed * 100003 + g
        a = make_agent(adj, w_a, s * 2 + 1)
        b = make_agent(adj, w_b, s * 2 + 2)
        black, white = (a, b) if g % 2 == 0 else (b, a)
        winner, _ = play_game(game, black, white)
        a_is_black = g % 2 == 0
        if winner == "draw":
            score += 0.5
        elif (winner == "B") == a_is_black:
            score += 1.0
    return score / games


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--boards", default="lowest",
                    help="'lowest' or comma list of spec keys "
                         f"({', '.join(SPECS)})")
    ap.add_argument("--generations", type=int, default=40)
    ap.add_argument("--pop", type=int, default=10)
    ap.add_argument("--elite", type=int, default=3)
    ap.add_argument("--games", type=int, default=6,
                    help="games per candidate fitness evaluation")
    ap.add_argument("--eval-games", type=int, default=12,
                    help="games vs the default weights each report")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", default=None,
                    help="model id; exports to web/models/<out>.{js,weights.json}")
    args = ap.parse_args()

    keys = LOWEST if args.boards == "lowest" else args.boards.split(",")
    for k in keys:
        if k not in SPECS:
            sys.exit(f"unknown board spec '{k}' (have: {', '.join(SPECS)})")
    rng = np.random.default_rng(args.seed)

    mu = flatten_weights(DEFAULT_WEIGHTS)
    sigma = 0.3 * np.abs(mu) + 0.02
    print(f"training on {keys}; {len(mu)} trainable weights; "
          f"pop {args.pop}, elite {args.elite}, {args.games} games/candidate")

    for gen in range(1, args.generations + 1):
        t0 = time.time()
        ref = unflatten_weights(mu)
        cands = [mu + sigma * rng.standard_normal(len(mu))
                 for _ in range(args.pop)]
        fits = [match(unflatten_weights(c), ref, keys, args.games,
                      seed=args.seed * 1000 + gen * 37 + i)
                for i, c in enumerate(cands)]
        order = np.argsort(fits)[::-1]
        elite = np.stack([cands[i] for i in order[: args.elite]])
        mu = 0.6 * mu + 0.4 * elite.mean(axis=0)
        sigma = 0.7 * sigma + 0.3 * (elite.std(axis=0) + 0.01)
        line = (f"gen {gen:3d}  fitness {np.mean(fits):.2f} "
                f"(best {max(fits):.2f})  sigma {sigma.mean():.3f}  "
                f"{time.time() - t0:.0f}s")
        if gen % 5 == 0 or gen == args.generations:
            wr = match(unflatten_weights(mu), DEFAULT_WEIGHTS, keys,
                       args.eval_games, seed=args.seed * 7919 + gen)
            line += f"  | vs default: {wr:.2f}"
        print(line, flush=True)

    if args.out:
        export(mu, args.out, keys)


def export(mu, out_id, keys):
    w = unflatten_weights(mu)
    mdir = os.path.join(ROOT, "web", "models")
    os.makedirs(mdir, exist_ok=True)
    with open(os.path.join(mdir, f"{out_id}.weights.json"), "w") as f:
        json.dump(w, f, indent=2)
    name = "HGNN " + out_id.replace("hgnn-", "").replace("-", " ")
    with open(os.path.join(mdir, f"{out_id}.js"), "w") as f:
        f.write(MODEL_JS.format(id=out_id, name=name))
    print(f"exported web/models/{out_id}.js + .weights.json "
          f"(trained on {','.join(keys)}) — run `node build.mjs` in web/")


if __name__ == "__main__":
    main()
