// Auto-generated by python/train/train_hgnn.py — do not edit.
// Trained instance of the built-in hierarchical engine; WEIGHTS is inlined
// by the build from the sibling .weights.json.
GeoAI.models.push({
  id: 'hgnn-medium',
  name: 'HGNN medium',
  levels: ["standard"],
  create(neighbors, opts) {
    const e = GeoAI.createEngine(neighbors, opts);
    if (WEIGHTS) e.setWeights(WEIGHTS);
    return e;
  },
});
