// Auto-generated by python/train/train_zero.py --export-web.
// The zero-style graph net running natively in the page: WEIGHTS carries the
// trained parameters (inlined by the build from the sibling .weights.json).
// The forward pass mirrors python/train/zeronet.py exactly.
(function () {
  const P = WEIGHTS.params, L = WEIGHTS.layers, D = WEIGHTS.hidden;

  function forward(adj, stones, toMove, mask) {
    const n = adj.length;
    let md = 1;
    for (let v = 0; v < n; v++) md = Math.max(md, adj[v].length);
    let H = new Array(n);                       // features -> first layer
    for (let v = 0; v < n; v++) {
      const c = stones[v];
      const x = [c === toMove ? 1 : 0, (c && c !== toMove) ? 1 : 0,
                 c === 0 ? 1 : 0, adj[v].length / md, 1];
      const h = new Float64Array(D);
      for (let j = 0; j < D; j++) {
        let s = P.b0[j];
        for (let i = 0; i < 5; i++) s += x[i] * P.W0[i][j];
        h[j] = s > 0 ? s : 0;
      }
      H[v] = h;
    }
    for (let l = 0; l < L; l++) {
      const Ws = P["Ws" + l], Wn = P["Wn" + l], b = P["b" + (l + 1)];
      const AH = new Array(n);
      for (let v = 0; v < n; v++) {
        const m = new Float64Array(D), a = adj[v];
        for (let k = 0; k < a.length; k++) {
          const hu = H[a[k]];
          for (let j = 0; j < D; j++) m[j] += hu[j];
        }
        if (a.length) for (let j = 0; j < D; j++) m[j] /= a.length;
        AH[v] = m;
      }
      const H2 = new Array(n);
      for (let v = 0; v < n; v++) {
        const h = new Float64Array(D);
        for (let j = 0; j < D; j++) {
          let s = b[j];
          for (let i = 0; i < D; i++)
            s += H[v][i] * Ws[i][j] + AH[v][i] * Wn[i][j];
          h[j] = s > 0 ? s : 0;
        }
        H2[v] = h;
      }
      H = H2;
    }
    const g = new Float64Array(D);
    for (let v = 0; v < n; v++)
      for (let j = 0; j < D; j++) g[j] += H[v][j] / n;
    const logits = new Float64Array(n + 1);
    for (let v = 0; v < n; v++) {
      let s = P.bp[0];
      for (let j = 0; j < D; j++) s += H[v][j] * P.wp[j];
      logits[v] = s;
    }
    let pl = P.bq[0], u = P.bv[0];
    for (let j = 0; j < D; j++) { pl += g[j] * P.wq[j]; u += g[j] * P.wv[j]; }
    logits[n] = pl;
    let mx = -Infinity;
    for (let i = 0; i <= n; i++) if (mask[i]) mx = Math.max(mx, logits[i]);
    let Z = 0;
    const probs = new Float64Array(n + 1);
    for (let i = 0; i <= n; i++) {
      probs[i] = mask[i] ? Math.exp(logits[i] - mx) : 0;
      Z += probs[i];
    }
    for (let i = 0; i <= n; i++) probs[i] /= Z || 1;
    return { probs, value: Math.tanh(u) };
  }

  GeoAI.models.push({
    id: "zero-all",
    name: "Zero zero-all",
    levels: ["casual", "standard"],
    supports: {"surfaces": ["cylinder", "klein", "mobius", "plane", "rp2", "sphere", "torus"], "meshes": ["square", "tri"], "incidence": ["vertices"]},
    create(neighbors, opts) {
      const level = (opts && opts.level) || "standard";
      return {
        forward(stones, color, mask) { return forward(neighbors, stones, color, mask); },
        pickMove(stones, color, o) {
          const n = neighbors.length;
          const legal = (o && o.legalMask) || null;
          const mask = new Uint8Array(n + 1);
          mask[n] = 1;
          for (let v = 0; v < n; v++)
            if (stones[v] === 0 && (!legal || legal[v])) mask[v] = 1;
          const { probs, value } = forward(neighbors, stones, color, mask);
          let a = n;
          if (level === "casual") {
            let r = Math.random();
            for (let i = 0; i <= n; i++) { r -= probs[i]; if (r <= 0) { a = i; break; } }
          } else {
            let best = -1;
            for (let i = 0; i <= n; i++)
              if (probs[i] > best) { best = probs[i]; a = i; }
          }
          return { move: a === n ? -1 : a,
                   value, reason: "zero policy v" + value.toFixed(2) };
        },
      };
    },
  });
})();
